### ISSUE TITLE
Improvement suggestion

### ISSUE THREAD

**Issue by johnemcbride** [tynor88/docker-socat#3]
I use this to route to services on docker containers which have been spun up without having ports opened originally.

To do this i start the socat container with a link to the target docker container and amended the run script to refer that host instead of obtaining from ifconfig.

potentially you could enhance this to check for the presence of such a variable to make this a true swiss army knife docker port opener.

**Comment by johnemcbride** [comment]
diff --git a/root/etc/services.d/socat/run b/root/etc/services.d/socat/run
index 769218b..39d0f3f 100644
--- a/root/etc/services.d/socat/run
+++ b/root/etc/services.d/socat/run
@@ -2,6 +2,6 @@
 
 umask 002
 
-s6-echo "Forwarding $LISTEN_PORT -> $FORWARD_PORT"
+s6-echo "Forwarding $LISTEN_PORT -> $FORWARD_SERVER:$FORWARD_PORT"
 
-exec socat tcp-listen:${LISTEN_PORT},fork tcp-connect:$(ip route | grep default | awk "{print \$3}"):${FORWARD_PORT}
+exec socat tcp-listen:${LISTEN_PORT},fork tcp-connect:${FORWARD_SERVER}:${FORWARD_PORT}

**Comment by johnemcbride** [comment]
then to invoke:
docker run   --name=socat   -e LISTEN_PORT=80   -e FORWARD_PORT=8000    -p:80:80  --link some-app:target_app   socat
(nb error in previous comment: FORWARD SEVER should be 'target_app')

**Comment by tynor88** [comment]
@johnemcbride Thanks for the suggestion.

Maybe you could make a PR for this? Preferably to the dev branch so we can test it first, before merging it to master.

**Comment by johnemcbride** [comment]
@tynor88  see #4.  Hope this helps.

**Comment by tynor88** [comment]
Closing as this have been merged into dev.
